<?php

return [
    'hello' => array(
        ['greeting', 'how are you'],
        [
            'Good to see you',
            'Hey, there',
            'Hello',
            'Hey',
            'Hi',
            'Hi, there',
            'Bonjour',
            'Howdy?',
            'How are things?',
            'What have you been up to?',
            'Look what the cat dragged in!',
            'What’s going on?',
            'How have you been?',
            'What’s up?',
            'Welcome',
            'Hi, fancy seeing you here',
            'I haven’t seen you in ages',
        ],
        ['greeting', 'hello', 'hi', 'hey', 'yo']
    ),
    'goodbye' => array(
    	['goodbye', 'acknowledgement'],
    	[
    		"Bye",
	        "Goodbye",
	        "See you later",
	        "I am leaving",
	        "Talk to you later",
	        "I have to go"
    	],
		['goodbye', 'bye', 'farewell', 'later', 'see you', 'talk to you']
    ),
    'greeting' => array(
        ['hello'],
        [
            'Greetings',
            'Good morning',
            'Good morning, sunshine!',
            'Mornin’ mi Amigo!',
            'Rise and shine!',
            'Morning!',
            'Good day to you!',
            'Good evening',
            'Good afternoon.',
        ],
        ['morning', 'afternoon', 'evening', 'day', 'early', 'wake', 'rise']
    ),
    'how are you' => array(
        ['status'],
        [
            'How are you feeling today?',
            'What’s new?',
            'How’s it going?',
            'How’s everything?',
            'How’s life?',
            'What’s happening?',
            'How do you do?',
            'What are you up to?',
            'How are you doing?',
            'How are you holding up?',
            'Wassup?',
            'How are things going?',
            'How have you been?',
        ],
        ['update', 'status', 'well', 'how']
    ),
    'status' => array(
        ['small talk', 'acknowledgement'],
        [
            'I’m fine.',
            'All good.',
            'Just living the dream.',
            'Excellent',
            'No complaints',
            'Can’t complain',
            'Everything’s good so far',
            'So far, so good',
            'Staying busy',
            'Just passing time',
            'It could be worse',
        ],
        ['good', 'fine', 'well', 'happy']
    ),
    'thank you' => array(
        ['you’re welcome'],
        [
            'Thank you',
            'Thanks',
            'Appreciated',
            'I appreciate it',
            'Wonderful',
            'You’re amazing',
            'Perfect',
        ],
        ['thanks', 'gratitude', 'appreciation']
    ),
    'you’re welcome' => array(
        ['small talk'],
        [
            'You’re welcome',
            'No problem',
            'No need',
            'No big deal',
            'Glad to help',
            'It’s no big deal',
            'No biggie',
            'I know you’d do the same for me',
            'Happy to be of service',
            'Much obliged',
            'Oh, think nothing of it!',
            'Glad to be of service',
            'It’s what I’m here for',
            'Just doing my job',
        ],
        ['welcome', 'obliged', 'service']
    ),
    'small talk' => array(
		['acknowledgement'],
		[
			'How’s the weather?',
			'What’s new?',
			'How’s it going?',
			'How’s everything?',
			'How’s life?',
			'What’s happening?',
			'How do you do?',
			'What are you up to?',
			'How are you doing?',
			'How are you holding up?',
			'Wassup?',
			'How are things going?',
			'How have you been?',
			"I can't experience weather, but I hope it's nice where you are!",
	        "Why don't scientists trust atoms? Because they make up everything!",
	        "I don't have a favorite color, but I think all colors are fascinating.",
	        "I don't listen to music, but I can help you find some if you like!",
	        "I don't watch movies, but I can help you find information about them.",
		],
		['talk', 'chat', 'conversation', 'discussion']
	),
    'excuse me' => array(
        ['confusion', 'acknowledgement'],
        [
            'Excuse me?',
            'Do you mind repeating that?',
            'Sorry, I didn’t hear what you said.',
            'Sorry, I didn’t catch that.',
            'Could you please repeat that?',
            'Would you mind repeating that?',
            'Pardon?',
            'Sorry',
            'I’m sorry, I don’t understand. Could you repeat that, please?',
            'Let me repeat that just to make sure?',
        ],
        ['excuse', 'pardon', 'sorry']
    ),
    'confusion' => array(
        ['request clarification', 'acknowledgement'],
        [
            'What is that?',
            'Please explain...',
            'I’m not sure what that is.',
            'What does that mean?',
            'Say more, please',
        ],
        ['confused', 'unknown', 'unaware', 'uninformed']
    ),
    'request clarification' => array(
        ['provide information'],
        [
            'Can you clarify?',
            'Could you elaborate on that?',
            'What exactly do you mean?',
            'Can you provide more details?',
            'I need more information to help you.',
        ],
        ['clarify', 'detail', 'explain', 'elaborate']
    ),
    'provide information' => array(
        ['acknowledgement'],
        [
            'Here’s what I found:',
            'Based on the information:',
            'According to the data:',
            'From what I can gather:',
            'The details are as follows:',
        ],
        ['information', 'details', 'data', 'facts']
    ),
    'command' => array(
        ['execution', 'clarification'],
        [
            'list all resources',
            'open file named "x"',
            'show me the news',
            'calculate the sum of x and y',
            'find the nearest coffee shop',
            'schedule a meeting with John on Friday',
        ],
        ['command', 'execute', 'perform', 'action']
    ),
    'execution' => array(
        ['confirmation', 'error handling'],
        [
            'Executing your command...',
            'Processing request...',
            'Working on it...',
            'Command in progress...',
            'Attempting to execute...',
        ],
        ['execution', 'process', 'action', 'running']
    ),
    'confirmation' => array(
        ['follow-up'],
        [
            'Done.',
            'Completed.',
            'Your request has been processed.',
            'I’ve finished executing the command.',
            'It’s all set.',
        ],
        ['confirmation', 'completed', 'done', 'finished']
    ),
    'error handling' => array(
        ['error response'],
        [
            'There was an error executing your command.',
            'I encountered a problem.',
            'Unable to complete your request.',
            'Something went wrong.',
            'The command failed.',
        ],
        ['error', 'problem', 'issue', 'failed']
    ),
    'error response' => array(
        ['retry', 'alternative'],
        [
            'Would you like to try again?',
            'Should I attempt a different approach?',
            'Can I try another method?',
            'Would you like to modify the command?',
        ],
        ['retry', 'alternative', 'again', 'different']
    ),
    'file management' => array(
		['file operation'],
		[
			'Open file',
			'Close file',
			'Save file',
			'Delete file',
			'Copy file',
			'Move file',
			'Rename file',
			'Create new file',
			'Edit file',
			'Print file',
			'Find file',
			"Move the file",
	        "Delete the file",
	        "Rename the file",
	        "Copy the file",
	        "How do I move a file?",
	        "I want to delete a file"
		],
		['file', 'document', 'folder', 'directory']
	),
	'file operation' => array(
		['file management', 'thank you'],
		[
			"You can move a file by saying 'move the file [file_name] to [destination]'.",
	        "To delete a file, you can say 'delete the file [file_name]'.",
	        "To rename a file, use 'rename the file [current_name] to [new_name]'.",
	        "You can copy a file by saying 'copy the file [file_name] to [destination]'."
		],
		['file', 'document', 'folder', 'directory', 'operation']
	),
	'list management' => array(
		['list operation'],
		[
			'Create a list',
			'Add item to list',
			'Remove item from list',
			'Edit list',
			'Delete list',
			'Show list',
			'Find list',
			'Print list',
			'Update list',
			"Create a new list",
	        "Add item to list",
	        "Show my lists",
	        "Delete list",
	        "How do I create a list?",
	        "I want to add an item to a list",
	        "Show me my lists"
	    ],
	    ['list', 'item', 'task', 'to-do']
	),
	'list operation' => array(
		['list management', 'thank you'],
		[
			"You can create a new list by saying 'create a new list [list_name]'.",
	        "To add an item to a list, use 'add [item] to the list [list_name]'.",
	        "To view your lists, say 'show my lists'.",
	        "To delete a list, you can say 'delete the list [list_name]'."
		],
		['list', 'item', 'task', 'to-do', 'operation']
	),
	'note management' => array(
		['note operation'],
		[
			'Create a note',
			'Add note',
			'Edit note',
			'Delete note',
			'Show note',
			'Find note',
			'Print note',
			'Update note',
			"Create a new note",
	        "Add a note",
	        "Show my notes",
	        "Delete note",
	        "How do I create a note?",
	        "I want to add a note",
	        "Show me my notes"
	    ],
	    ['note', 'memo', 'reminder', 'message']
	),
	'note operation' => array(
		['note management', 'thank you'],
		[
			"You can create a new note by saying 'create a new note [note_title]'.",
	        "To add a note, use 'add note [note_content]'.",
	        "To view your notes, say 'show my notes'.",
	        "To delete a note, you can say 'delete the note [note_title]'."
		],
		['note', 'memo', 'reminder', 'message', 'operation']
	),
	'weather' => array(
		['weather forecast'],
		[
			'What is the weather today?',
			'What is the weather forecast?',
			'How is the weather?',
			'Is it going to rain today?',
			'What is the temperature?',
			'What is the weather like?',
			'How is the weather today?',
			'What is the weather report?',
			'What is the weather condition?',
			'What is the weather in [city]?',
			'What is the weather like in [city]?',
			'What is the temperature in [city]?',
			'What is the weather forecast for [city]?',
			'What is the weather condition in [city]?',
			'What is the weather report for [city]?',
			'What is the weather like in [city]?',
			'How is the weather in [city]?',
			'What is the weather like in [city] today?',
			'What is the temperature in [city] today?',
			'What is the weather forecast for [city] today?',
			'What is the weather condition in [city] today?',
			'What is the weather report for [city] today?',
			'What is the weather like in [city] today?',
			'How is the weather in [city] today?',
		],
		['weather', 'forecast', 'temperature', 'condition', 'rain', 'sun', 'cloud', 'wind', 'city']
	),
	'weather forecast' => array(
		['weather', 'thank you'],
		[
	        "You can check the weather by saying 'weather now' or 'show the weather for [location]'."
		],
		['weather', 'forecast', 'temperature', 'condition', 'city']
	),
	'calculator' => array(
		['math operation'],
		[
			'Calculate the sum of x and y',
			'What is the result of x plus y?',
			'What is the sum of x and y?',
			'Add x and y',
			'What is x plus y?',
			'Calculate the difference of x and y',
			'What is the result of x minus y?',
			'What is the difference of x and y?',
			'Subtract y from x',
			'What is x minus y?',
			'Calculate the product of x and y',
			'What is the result of x times y?',
			'What is the product of x and y?',
			'Multiply x and y',
			'What is x times y?',
			'Calculate the quotient of x and y',
			'What is the result of x divided by y?',
			'What is the quotient of x and y?',
			'Divide x by y',
			'What is x divided by y?',
			'Calculate the remainder of x divided by y',
			'What is the result of x modulo y?',
			'What is the remainder of x divided by y?',
			'Find the remainder of x divided by y',
			'What is the modulo of x and y?',
			'What is the remainder of x and y?',
			'Calculate the square root of x',
			'What is the square root of x?',
			'Find the square root of x',
			'What is the square root of x?',
			'Calculate the power of x to the y',
			'What is the result of x to the power of y?',
			'What is the power of x to the y?',
			'Find x to the power of y',
			'What is x to the power of y?',
		],
		['calculate', 'sum', 'difference', 'product', 'quotient', 'remainder', 'modulo', 'square root', 'power']
	),
	'math operation' => array(
		['calculator', 'thank you'],
		[
			"You can perform math operations by saying 'calculate the sum of x and y'.",
	        "To find the square root, use 'calculate the square root of x'.",
	        "To calculate the power, say 'calculate the power of x to the y'.",
	        "Ask 'what is the sum of x and y?' to calculate the sum of two numbers.",
	        "Say 'what is the square root of x?' to find the square root of a number.",
		],
		['math', 'operation', 'calculate', 'sum', 'difference', 'product', 'quotient', 'remainder', 'modulo', 'square root', 'power']
	),
	'how to' => array(
		['instruction'],
		[
			'How do I create a list?',
			'How do I add an item to a list?',
			'How do I delete a list?',
			'How do I create a note?',
			'How do I add a note?',
			'How do I delete a note?',
			'How do I move a file?',
			'How do I delete a file?',
			'How do I rename a file?',
			'How do I copy a file?',
			'How do I find a file?',
			'How do I create a list?',
			'How do I add an item to a list?',
			'How do I show my lists?',
			'How do I delete a list?',
			'How do I create a note?',
			'How do I add a note?',
			'How do I show my notes?',
			'How do I delete a note?',
			'How do I check the weather?',
			'How do I calculate the sum of x and y?',
			'How do I find the square root of x?',
			'How do I calculate the power of x to the y?',
			"Can you show me how to",
	        "How do I",
	        "Can you explain how to",
	        "Can you guide me on how to",
	        "Can you provide a tutorial on how to",
	        "Explain how to",
	        "Guide me on how to",
	        "Step by step tutorial on how to",
	        "Steps on how to",
		],
		['instruction', 'how to', 'guide', 'tutorial']
	),
	'instruction' => array(
		['how to', 'thank you'],
		[
			"You can get how-to information by saying 'how to [task]' or 'show me how to [task]'.",
			"Say 'how do I create a list?' to learn how to create a list.",
			"Ask 'how do I add an item to a list?' to learn how to add an item to a list.",
		],
		['instruction', 'how to', 'guide', 'tutorial']
	),
	'schedule management' => array(
		['schedule operation'],
		[
			'Schedule a meeting',
			'Add event to calendar',
			'Remove event from calendar',
			'Edit event in calendar',
			'Delete event from calendar',
			'Show calendar',
			'Find event in calendar',
			'Print calendar',
			'Update calendar',
			"Schedule a meeting with [person] on [date]",
	        "Add an event to my calendar",
	        "Remove an event from my calendar",
	        "Edit an event in my calendar",
	        "Delete an event from my calendar",
	        "Show me my calendar",
	        "Find an event in my calendar",
	        "Print my calendar",
	        "Update my calendar",
	        "Schedule an event",
	        "Create a reminder",
	        "Set a reminder",
	        "Add to my schedule",
        	"Calendar",
	    ],
	    ['schedule', 'meeting', 'event', 'calendar', 'appointment']
	),
	'schedule operation' => array(
		['schedule management', 'thank you'],
		[
			"You can schedule a meeting by saying 'schedule a meeting with [person] on [date]'.",
	        "To add an event to your calendar, use 'add an event to my calendar'.",
	        "To view your calendar, say 'show me my calendar'.",
	        "To delete an event from your calendar, you can say 'delete an event from my calendar'.",
	        "Say 'schedule a meeting with [person] on [date]' to schedule a meeting.",
	        "Simply ask 'add an event to my calendar' to add an event to your calendar."
		],
		['schedule', 'meeting', 'event', 'calendar', 'appointment', 'operation']
	),
	'search' => array(
		['search operation'],
		[
			'Search for information',
			'Find details',
			'Look up data',
			'Locate resources',
			'Explore content',
			'Investigate topic',
			'Check for answers',
			'Query database',
			'Seek out information',
			"Search for [query]",
	        "Find [query]",
	        "Look up [query]",
	        "Locate [query]",
	        "Explore [query]",
	        "Investigate [query]",
	        "Check for [query]",
	        "Query [query]",
	        "Seek out [query]",
	        "Search for information on [query]",
	        "Find details about [query]",
	        "Look up data on [query]",
	        "Locate resources for [query]",
	        "Explore content about [query]",
	        "Investigate topic on [query]",
	        "Check for answers on [query]",
	        "Query database for [query]",
	        "Seek out information on [query]",
	        "Search for [query] information",
	        "Find [query] details",
	        "Look up [query] data",
	        "Locate [query] resources",
	        "Explore [query] content",
	        "Investigate [query] topic",
	        "Check for [query] answers",
	        "Query [query] database",
	        "Seek out [query] information",
	    ],
	    ['search', 'find', 'look up', 'locate', 'explore', 'investigate', 'check', 'query', 'seek out', 'information', 'details', 'data', 'resources', 'content', 'topic', 'answers', 'database']
	),
	'search operation' => array(
		['search', 'thank you'],
		[
			"You can search for information by saying 'search for [query]' or 'find [query]'.",
			"Ask 'search for [query]' to find information on a specific topic.",
	        "Say 'look up [query]' to explore data on a particular subject.",
        	"To look something up, use 'find [query]'."
		],
		['search', 'find', 'look up', 'locate', 'explore', 'investigate', 'check', 'query', 'seek out', 'information', 'details', 'data', 'resources', 'content', 'topic', 'answers', 'database']
	),
	'name' => array(
		['introduction'],
		[
			"What is your name?",
			"Who are you?",
			"May I know your name?",
			"Can you tell me your name?",
			"What should I call you?",
			"Who am I speaking to?",
			"What do you go by?",
			"Who is this?",
			"Who is on the line?",
			"Who is speaking?",
			"Who is this speaking?",
		],
		['name', 'identity', 'who', 'you']
	),
	'introduction' => array(
		['name', 'thank you'],
		[
			"My name is Chatbot, how can I assist you today?",
			"I am Chatbot, here to help you with your queries.",
			"You can call me Chatbot, what can I do for you?",
			"I go by Chatbot, how may I help you?",
			"I am Chatbot, your virtual assistant. How can I assist you?",
			"I am Chatbot, at your service. How may I help you?",
			"I am Chatbot, your personal assistant. What can I do for you?",
			"I am Chatbot, ready to help you. How may I assist you?",
			"I am Chatbot, here to assist you. What can I do for you?",
			"I am Chatbot, your friendly assistant. How may I help you?",
			"I am Chatbot, your helpful assistant. What can I do for you?",
			"I am Chatbot, your trusty assistant. How may I assist you?",
			"I am Chatbot, your reliable assistant. What can I do for you?",
			"I am Chatbot, your virtual helper. How may I help you?",
			"I am Chatbot, your digital assistant. What can I do for you?",
			"I am Chatbot, your AI assistant. How may I assist you?",
			"I am Chatbot, your chat assistant. What can I do for you?",
			"I am Chatbot, your conversation assistant. How may I help you?",
			"I am Chatbot, your talk assistant. What can I do for you?",
			"I am Chatbot, your messaging assistant. How may I assist you?",
			"I am Chatbot, your communication assistant. What can I do for you?",
			"I am Chatbot, your support assistant. How may I help you?",
			"I am Chatbot, your service assistant. What can I do for you?",
			"I am Chatbot, your help assistant. How may I assist you?",
			"I am Chatbot, your assistance assistant. What can I do for you?",
			"I am Chatbot, your aid assistant. How may I help you?",
			"I am Chatbot, your backup assistant. What can I do for you?",
		],
		['name', 'identity', 'who', 'you']
	),
	'complaint' => array(
		['apology', 'acknowledgement'],
		[
			"I have a complaint",
			"I need to make a complaint",
			 "This isn't working",
	        "Something went wrong",
	        "I need to report an issue",
    	    "This is broken",
    	    "I’m not happy with this",
    	    "I’m dissatisfied with this",
    	    "I’m not satisfied with this",
    	    "This is unacceptable",
    	    "This is not what I wanted",
    	    "This is not what I expected",
    	    "This is not what I asked for",
    	    "That's wrong",
    	    "That's not right",
    	],
    	['complaint', 'issue', 'problem', 'error', 'wrong', 'dissatisfied', 'unhappy', 'unsatisfied', 'unacceptable', 'unexpected', 'not right']
	),
	'apology' => array(
		['acknowledgement'],
		[
			"I’m sorry to hear that. Can you please provide more details about the issue?",
        	"I apologize for the inconvenience. Let's see how we can fix this.",
        	"I’m sorry to hear that. Let's work together to resolve this.",
        ],
		['apology', 'sorry', 'inconvenience', 'issue', 'problem', 'resolve']
	),
	'goal' => array(
		['goal response'],
		[
			"Help me set a goal",
	        "I want to achieve my goals",
	        "Can you help me with goal setting?",
	        "How do I set a goal?",
        	"Assist me with my goals",
		],
		['goal', 'objective', 'aim', 'purpose', 'accomplish']
	),
	'goal response' => array(
		['goal', 'thank you'],
		[
			"You can set a goal by saying 'help me set a goal' or 'I want to achieve my goals'.",
			"Sure! Let's start by defining your goal. What would you like to achieve?",
        	"To set a goal, think about what you want to accomplish and set a specific, measurable target."
		],
		['goal', 'objective', 'aim', 'purpose', 'accomplish']
	),
    'unknown.intent' => array(
        ['request clarification', 'acknowledgement'],
        [
            "I'm not sure I understand.",
            "I didn't catch that. Could you rephrase?",
            "I'm still learning. Can you say that another way?",
            "Sorry, I don't have enough context for that yet.",
            "Could you give me a little more detail?",
        ],
        []
    ),
];
