<?php

return [
    'hello' => [
        'priority' => 12,
        'keywords' => [
            'hello',
            'hi',
            'hey',
            'hiya',
            'yo',
        ],
    ],
    'goodbye' => [
        'priority' => 12,
        'keywords' => [
            'goodbye',
            'bye',
            'see you',
            'later',
            'take care',
        ],
    ],
    'greeting' => [
        'priority' => 11,
        'keywords' => [
            'good morning',
            'good afternoon',
            'good evening',
            'greetings',
        ],
    ],
    'how are you' => [
        'priority' => 10,
        'keywords' => [
            'how are you',
            'how is it going',
            'how have you been',
            'what\'s up',
        ],
    ],
    'status' => [
        'priority' => 11,
        'keywords' => [
            'status',
            'update',
            'status report',
            'system status',
        ],
    ],
    'thank you' => [
        'priority' => 10,
        'keywords' => [
            'thanks',
            'thank you',
            'appreciate it',
            'appreciation',
        ],
    ],
    'you\'re welcome' => [
        'priority' => 10,
        'keywords' => [
            'you\'re welcome',
            'no problem',
            'no worries',
            'glad to help',
        ],
    ],
    'file management' => [
        'priority' => 12,
        'keywords' => [
            'file',
            'files',
            'document',
            'folder',
            'directory',
            'open file',
            'rename file',
            'delete file',
            'copy file',
            'move file',
            'find file',
        ],
    ],
    'file operation' => [
        'priority' => 12,
        'keywords' => [
            'move file',
            'delete file',
            'rename file',
            'copy file',
            'save file',
            'open file',
            'file operation',
        ],
    ],
    'list management' => [
        'priority' => 12,
        'keywords' => [
            'list',
            'lists',
            'checklist',
            'task list',
            'to-do',
            'todo',
            'add item',
            'remove item',
            'create list',
            'delete list',
            'show list',
        ],
    ],
    'list operation' => [
        'priority' => 12,
        'keywords' => [
            'add item',
            'remove item',
            'show list',
            'delete list',
            'create list',
            'list item',
        ],
    ],
    'note management' => [
        'priority' => 12,
        'keywords' => [
            'note',
            'notes',
            'memo',
            'create note',
            'delete note',
            'show note',
        ],
    ],
    'note operation' => [
        'priority' => 12,
        'keywords' => [
            'add note',
            'delete note',
            'show note',
            'note content',
        ],
    ],
    'schedule management' => [
        'priority' => 12,
        'keywords' => [
            'schedule',
            'calendar',
            'appointment',
            'meeting',
            'event',
            'reminder',
        ],
    ],
    'schedule operation' => [
        'priority' => 12,
        'keywords' => [
            'add event',
            'delete event',
            'remove event',
            'schedule meeting',
            'calendar entry',
        ],
    ],
    'weather' => [
        'priority' => 11,
        'keywords' => [
            'weather',
            'forecast',
            'temperature',
            'rain',
            'cloud',
            'wind',
            'sunny',
        ],
    ],
    'calculator' => [
        'priority' => 11,
        'keywords' => [
            'calculate',
            'sum',
            'add',
            'subtract',
            'multiply',
            'divide',
            'math',
            'equation',
        ],
    ],
    'math operation' => [
        'priority' => 11,
        'keywords' => [
            'math',
            'calculation',
            'arithmetic',
            'sum',
            'difference',
            'product',
            'quotient',
        ],
    ],
    'how to' => [
        'priority' => 10,
        'keywords' => [
            'how to',
            'how do i',
            'show me how',
            'guide',
            'tutorial',
            'steps',
            'explain',
        ],
        'exclude' => [
            'how',
        ],
    ],
    'name' => [
        'priority' => 12,
        'keywords' => [
            'name',
            'who are you',
            'who is this',
            'what do you go by',
            'your name',
            'identity',
        ],
    ],
    'complaint' => [
        'priority' => 11,
        'keywords' => [
            'complaint',
            'issue',
            'problem',
            'broken',
            'not working',
        ],
    ],
    'goal' => [
        'priority' => 11,
        'keywords' => [
            'goal',
            'objective',
            'aim',
            'target',
        ],
    ],
    'search' => [
        'priority' => 6,
        'keywords' => [
            'search',
            'look up',
            'lookup',
            'google',
            'web search',
            'browse',
            'research',
            'find',
            'query',
        ],
        'exclude' => [
            'information',
            'details',
            'data',
            'resources',
            'content',
            'topic',
            'answers',
            'database',
        ],
    ],
];
