<?php

return [
    'hello' => [
        'priority' => 12,
        'keywords' => [
            'hello',
            'hi',
            'hey',
            'hiya',
            'yo',
        ],
    ],
    'goodbye' => [
        'priority' => 12,
        'keywords' => [
            'goodbye',
            'bye',
            'see you',
            'later',
            'take care',
        ],
    ],
    'greeting' => [
        'priority' => 11,
        'keywords' => [
            'good morning',
            'good afternoon',
            'good evening',
            'greetings',
        ],
    ],
    'how are you' => [
        'priority' => 10,
        'keywords' => [
            'how are you',
            'how is it going',
            'how have you been',
            'what\'s up',
        ],
    ],
    'status' => [
        'priority' => 11,
        'train_statements' => false,
        'keywords' => [
            'what is your status',
            'status',
            'update',
            'status report',
            'system status',
        ],
    ],
    'thank you' => [
        'priority' => 10,
        'keywords' => [
            'thanks',
            'thank you',
            'appreciate it',
            'appreciation',
        ],
    ],
    'you\'re welcome' => [
        'priority' => 10,
        'keywords' => [
            'you\'re welcome',
            'you are welcome',
            'no problem',
            'no worries',
            'glad to help',
        ],
    ],
    'file management' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'file',
            'files',
            'document',
            'folder',
            'directory',
            'open file',
            'rename file',
            'delete file',
            'copy file',
            'move file',
            'find file',
        ],
    ],
    'file operation' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'move file',
            'move the file',
            'delete file',
            'delete the file',
            'rename file',
            'rename the file',
            'copy file',
            'copy the file',
            'save file',
            'open file',
            'file operation',
        ],
    ],
    'list management' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'create a list',
            'list',
            'lists',
            'checklist',
            'task list',
            'to-do',
            'todo',
            'add item',
            'remove item',
            'create list',
            'delete list',
            'show list',
        ],
    ],
    'list operation' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'add item',
            'add item to list',
            'remove item',
            'show list',
            'delete list',
            'create list',
            'list item',
        ],
    ],
    'note management' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'note',
            'notes',
            'memo',
            'create note',
            'delete note',
            'show note',
        ],
    ],
    'note operation' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'add note',
            'delete note',
            'delete the note',
            'show note',
            'note content',
        ],
    ],
    'schedule management' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'show me my calendar',
            'schedule',
            'calendar',
            'appointment',
            'meeting',
            'event',
            'reminder',
        ],
    ],
    'schedule operation' => [
        'priority' => 12,
        'train_statements' => false,
        'keywords' => [
            'add event',
            'add an event',
            'add an event to my calendar',
            'delete event',
            'remove event',
            'schedule meeting',
            'calendar entry',
        ],
    ],
    'weather' => [
        'priority' => 11,
        'keywords' => [
            'weather',
            'forecast',
            'temperature',
            'rain',
            'cloud',
            'wind',
            'sunny',
        ],
    ],
    'calculator' => [
        'priority' => 11,
        'keywords' => [
            'calculate',
            'sum',
            'add',
            'subtract',
            'multiply',
            'divide',
            'math',
            'equation',
        ],
    ],
    'math operation' => [
        'priority' => 13,
        'train_statements' => false,
        'keywords' => [
            'math operation',
            'math',
            'calculation',
            'arithmetic',
            'sum',
            'difference',
            'product',
            'quotient',
        ],
    ],
    'small talk' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'talk',
            'chat',
            'conversation',
            'small talk',
        ],
    ],
    'joke' => [
        'priority' => 13,
        'keywords' => [
            'tell me a joke',
            'joke',
            'funny',
            'make me laugh',
            'humor',
        ],
    ],
    'joke response' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'joke',
            'funny',
            'humor',
        ],
    ],
    'weather forecast' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'weather',
            'forecast',
            'temperature',
            'condition',
            'city',
        ],
    ],
    'time' => [
        'priority' => 13,
        'keywords' => [
            'what time is it',
            'tell me the time',
            'current time',
            'what is the date',
            'tell me the date',
            'time',
            'date',
            'clock',
        ],
    ],
    'timeanddate response' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'time',
            'date',
            'clock',
        ],
    ],
    'instruction' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'instruction',
            'how to',
            'guide',
            'tutorial',
        ],
    ],
    'how to' => [
        'priority' => 10,
        'keywords' => [
            'how to',
            'how do i',
            'show me how',
            'guide',
            'tutorial',
            'steps',
            'explain',
        ],
        'exclude' => [
            'how',
        ],
    ],
    'name' => [
        'priority' => 12,
        'keywords' => [
            'name',
            'who are you',
            'who is this',
            'what do you go by',
            'your name',
            'identity',
        ],
    ],
    'complaint' => [
        'priority' => 11,
        'keywords' => [
            'complaint',
            'issue',
            'problem',
            'broken',
            'not working',
        ],
    ],
    'goal' => [
        'priority' => 11,
        'keywords' => [
            'goal',
            'objective',
            'aim',
            'target',
        ],
    ],
    'provide information' => [
        'priority' => 10,
        'train_statements' => false,
        'keywords' => [
            'here is what i found',
            'information',
            'details',
            'data',
            'facts',
        ],
    ],
    'command' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'command',
            'execute',
            'perform',
            'action',
        ],
    ],
    'execution' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'execution',
            'process',
            'action',
            'running',
        ],
    ],
    'confirmation' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'confirmation',
            'completed',
            'done',
            'finished',
        ],
    ],
    'error handling' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'error',
            'problem',
            'issue',
            'failed',
        ],
    ],
    'error response' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'retry',
            'alternative',
            'again',
            'different',
        ],
    ],
    'introduction' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'name',
            'identity',
            'assistant',
        ],
    ],
    'apology' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'apology',
            'sorry',
            'inconvenience',
            'resolve',
        ],
    ],
    'goal response' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'goal',
            'objective',
            'aim',
            'purpose',
        ],
    ],
    'unknown.intent' => [
        'priority' => 4,
        'train_statements' => false,
        'keywords' => [
            'unknown',
            'random input tokens',
        ],
    ],
    'search' => [
        'priority' => 6,
        'keywords' => [
            'search',
            'look up',
            'lookup',
            'google',
            'web search',
            'browse',
            'research',
            'find',
            'query',
        ],
        'exclude' => [
            'information',
            'details',
            'data',
            'resources',
            'content',
            'topic',
            'answers',
            'database',
        ],
    ],
    'search operation' => [
        'priority' => 8,
        'train_statements' => false,
        'keywords' => [
            'search',
            'find',
            'look up',
            'lookup',
            'query',
        ],
    ],
];
